# Generated by Django 5.1.1 on 2024-11-09 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conexion_id', models.CharField(max_length=100)),
                ('osmid', models.JSONField()),
                ('id_inicio', models.CharField(max_length=100)),
                ('id_fin', models.CharField(max_length=100)),
                ('oneway', models.JSONField()),
                ('lanes', models.CharField(blank=True, max_length=10, null=True)),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('highway', models.CharField(max_length=100)),
                ('maxspeed', models.CharField(blank=True, max_length=10, null=True)),
                ('reversed', models.JSONField()),
                ('length', models.FloatField()),
                ('junction', models.CharField(blank=True, max_length=100, null=True)),
                ('bridge', models.CharField(blank=True, max_length=100, null=True)),
                ('access', models.CharField(blank=True, max_length=100, null=True)),
                ('geometry', models.JSONField()),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones', to='Red_Internet.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodo_id', models.CharField(max_length=100)),
                ('y', models.FloatField()),
                ('x', models.FloatField()),
                ('street_count', models.IntegerField()),
                ('highway', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('geometry', models.JSONField()),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='Red_Internet.distrito')),
            ],
        ),
    ]
