# Generated by Django 5.1.1 on 2024-10-31 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('nodo_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_final', to='red.nodo')),
                ('nodo_inicial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_inicial', to='red.nodo')),
            ],
        ),
        migrations.DeleteModel(
            name='Conexion',
        ),
    ]
