# Generated by Django 5.1.1 on 2024-10-31 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0002_ruta_delete_conexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='geometria',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nodo_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_finales', to='red.nodo'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nodo_inicial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_iniciales', to='red.nodo'),
        ),
    ]
